### ISSUE TITLE
UI don't mint NFT anymore

### ISSUE THREAD

**Issue by Nicksart** [zaabstudio/candy-machine-zaab-ui#1]
After the last update of metaplex cm v2 your UI don't mint any nft. When i click mint i just send 0.01 sol to CM address and get unknow token  https://prnt.sc/Epz6HOaRVqJ2 this is the transaction: https://solscan.io/tx/5kvqwt5GoEkYvePFKNj23MJcEXqpk38hgumYtSWAEJkj91R43sKxjBghiHi5RboLyHL9kQijCq1aZc6bn4z4kHux
Hope you will fix it =) You have best UI for candy machine mint in the world)))) also it will be great to see multi mint feature (option to pick how much nft i want to mint)

**Comment by crazyrick4** [comment]
Hey @Nicksart, apologies for the late response.
But for the past months it is non-working, will deprecate it soon for an updated version for CMv3 & Aptos CM.

**Comment by zaabstudio** [comment]
CMv3 is supported as of the latest update with multi mint functionality!

**Comment by Nicksart** [comment]
hope you will push multi groups minting UI that would be incredible!

пн, 6 февр. 2023 г. в 19:18, Zaab Studio ***@***.***>:
